-- Reviewed Phase 2 research content. No datasets or weights are imported.
UPDATE roadmap_phases SET status='In Progress', description='Initial landscape research is complete. Collaborator mapping, formal provenance auditing and consultation continue.',updated_at=CURRENT_TIMESTAMP WHERE id='phase-0';
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('m0','phase-0','Initial Igbo AI technology landscape review','Completed',0) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('phase0-inventory','phase-0','Initial dataset and model inventory','Completed',1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('phase0-licences','phase-0','Initial licensing landscape review','Completed',2) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('phase0-gaps','phase-0','Identification of major technical gaps','Completed',3) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('m1','phase-0','Potential collaborator and research partner mapping','In Progress',4) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('phase0-provenance','phase-0','Formal dataset provenance audit','Planned',5) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('phase0-consultation','phase-0','Academic and community consultation','Planned',6) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO roadmap_milestones(id,phase_id,title,status,sort_order) VALUES('m2','phase-0','Initial benchmark specification','Planned',7) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status=excluded.status,sort_order=excluded.sort_order;
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('igboapi','Nkọwa okwu / IgboAPI','Nkọwa okwu','Pronunciation / Linguistics','Dialect-aware dictionary entries, meanings, example sentences and pronunciation recordings. A relevant starting point for lexical and dialect research.','https://docs.igboapi.com/igbo_api/overview','API terms; data and audio rights require review','https://igboapi.com/terms','Permission review','Potential collaboration','API access does not itself grant unrestricted training or redistribution rights. Review each data release and obtain permission where necessary.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('waxal','Google WAXAL — Igbo TTS','Google Research / Media Trust','Dataset','High-quality recorded speech for TTS research and possible baseline development. The Igbo subset is listed under Media Trust in the current dataset card.','https://huggingface.co/datasets/google/WaxalNLP','CC BY-SA 4.0 for the listed Igbo TTS subset','https://huggingface.co/datasets/google/WaxalNLP','Share-alike review','Reuse','Initial assessment of the current card: licences differ by provider. Audit the chosen version, attribution, share-alike obligations and recording provenance before reuse.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('common-voice','Mozilla Common Voice — Igbo','Mozilla Foundation / Common Voice','Dataset','Community read speech relevant to ASR, speaker variation and robustness. Review validated splits and sampling coverage before experiments.','https://mozilladatacollective.com/datasets/cmqioflak00zwnr073z9m9cra','CC0-1.0; platform conditions also apply','https://mozilladatacollective.com/datasets/cmqioflak00zwnr073z9m9cra','Platform conditions','Reuse','Reviewed release: Scripted Speech 26.0, June 2026. The datasheet prohibits speaker identification and re-hosting or re-sharing. Record access terms separately from the licence label.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('fleurs','Google FLEURS','Google Research','Dataset','Multilingual speech benchmark including Igbo, useful for comparative ASR evaluation and reproducible evaluation splits.','https://huggingface.co/datasets/google/fleurs','CC BY 4.0; verify selected release','https://huggingface.co/datasets/google/fleurs','Attribution review','Benchmark','Keep benchmark test data separate from training. Review domain, dialect and speaker coverage rather than treating one benchmark as complete language coverage.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('african-voices','African Voices / Data Science Nigeria','Data Science Nigeria','Dataset','Nigerian-language speech including Igbo, potentially significant for speech research. Metadata and permissions need a formal audit before ingestion.','https://africanvoices.io/terms-of-use','CC BY 4.0 default stated alongside platform restrictions','https://africanvoices.io/terms-of-use','Permission review','Investigate','Reconcile dataset-specific permissions and platform terms, review consent and version provenance. This is the Data Science Nigeria platform, distinct from other projects with similar names.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('ikengatts','IkengaTTS','chimezie90','TTS','An Igbo F5-TTS adaptation demonstrating meaningful ongoing Igbo speech synthesis work. An important reference for future comparison.','https://huggingface.co/chimezie90/igbo-tts-f5','CC BY-NC-SA 4.0 stated by model card','https://huggingface.co/chimezie90/igbo-tts-f5/blob/main/README.md','Non-commercial restrictions','Benchmark','Respect the model, base-model and data conditions. Published performance claims have not been independently reproduced by Igbo AI. Investigate explicit tone, phoneme and dialect supervision through controlled comparisons.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('mms','Meta MMS','Meta AI','ASR','Multilingual ASR and TTS research baselines. Model families and language checkpoints must be checked individually.','https://huggingface.co/facebook/mms-tts','TTS weights: CC BY-NC 4.0','https://huggingface.co/facebook/mms-tts','Non-commercial restrictions','Benchmark','MMS is a research/reference baseline, not an assumed permissive production foundation. Confirm Igbo coverage for the exact task and checkpoint before evaluation.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('ncair-asr','NCAIR / Awarri — Igbo ASR','NCAIR / Awarri','ASR','An Igbo Whisper Small adaptation within Nigerian language AI initiatives. Evidence of an active national speech research ecosystem.','https://huggingface.co/NCAIR1/Igbo-ASR','Custom research and innovation terms','https://huggingface.co/NCAIR1/Igbo-ASR?library=transformers','Permission review','Benchmark','The published terms include attribution, use limits and separate commercial licensing. Audit exact release terms before use. No partnership with Igbo AI is implied.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('natlas','N-ATLaS','NCAIR / Awarri','Language Model','A multilingual language model with Igbo among its target languages. A reference for later language-understanding evaluation.','https://huggingface.co/NCAIR1/N-ATLaS','Release and base-model conditions require review','https://huggingface.co/NCAIR1/N-ATLaS','Further licence audit required','Investigate','Review model and underlying Llama conditions independently. Igbo AI has not independently evaluated this model or confirmed a collaboration.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('igbobert','IgboBERT','Chukwuneke, Ezeani, Rayson and El-Haj','NLP','Igbo-specific transformer representations and named entity recognition research. Prior work that can inform future text-processing and language-understanding experiments.','https://aclanthology.org/2022.lrec-1.547/','Paper access does not establish model/data reuse rights','https://aclanthology.org/2022.lrec-1.547/','Further licence audit required','Investigate','LREC 2022. Verify checkpoint and corpus licences separately. Possible relevance to normalisation and diacritics is a future research direction, not a demonstrated capability claimed here.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('igboberta','IgboBERTa','AfricaNLP 2024 research contribution','NLP','Igbo text representation research, including evaluation on named entity recognition. A further reference for Igbo NLP.','https://openreview.net/pdf?id=OmCAN790Qj','Checkpoint and corpus terms require review','https://openreview.net/pdf?id=OmCAN790Qj','Further licence audit required','Investigate','Paper identified through its indexed AfricaNLP 2024 record. Full-text retrieval required a browser challenge during this review; verify the complete paper, authorship and artefacts before reuse.','2026-09-05','0','Published');
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status) VALUES('masakhane','Masakhane','Masakhane research community','Research Community','An African NLP ecosystem covering translation, named entity recognition, classification, question answering and evaluation.','https://www.masakhane.io','Resource-specific licences','https://github.com/masakhane-io','Further licence audit required','Potential collaboration','Engage respectfully with existing researchers. Each dataset, model and code repository has its own terms and language coverage. Community membership does not establish a formal project partnership.','2026-09-05','0','Published');
INSERT INTO research_updates(id,slug,title,summary,content,author_organisation,status,published_at,seo_description) VALUES('landscape-review-v01','igbo-ai-landscape-review-v0-1','Igbo AI Landscape Review v0.1','What already exists, what we can build upon, and what still needs to be built.','## Start by acknowledging the work

Igbo AI began by examining the existing ecosystem. Igbo language technology already has valuable datasets, lexical resources, trained systems and research communities. Our responsibility is to understand this work, credit it accurately and determine where responsible reuse can support new research.

The initial review covered speech and text datasets, ASR, TTS, Igbo NLP representations, language models, dialect and pronunciation resources, tone and diacritic research, licensing and African NLP communities. Its purpose was to identify useful foundations and missing infrastructure. This is a landscape review, not a completed dataset provenance audit or an independent reproduction of model results.

## Lexical and linguistic foundations

Nkọwa okwu / IgboAPI connects dictionary data with dialect variants, example sentences and pronunciation recordings. It is especially relevant to the questions behind IgboPronounce and dialect-aware speech. We will distinguish software access from the rights attached to dictionary material and recordings before selecting any training input.

IgboBERT and IgboBERTa demonstrate prior work in Igbo text representations and NLP. Such work can inform future investigations into normalisation, diacritics and language understanding. We do not assume that named entity recognition results establish performance on these other tasks.

## Speech data: useful resources, different conditions

Google WAXAL includes high-quality Igbo TTS material. The current dataset card lists the Media Trust Igbo subset under CC BY-SA 4.0; licences vary between providers. That makes release-specific review essential, even when a collection is described broadly as open.

Mozilla Common Voice Igbo provides community speech relevant to ASR, speaker variation and robustness. The reviewed release lists CC0 together with platform conditions against speaker identification and re-sharing. Google FLEURS offers an Igbo-inclusive multilingual benchmark useful for comparative ASR research. Evaluation splits must remain separate from training data.

African Voices, operated by Data Science Nigeria, is a potentially significant Nigerian-language speech resource. Before deciding how it can be used, we need to reconcile dataset-specific rights, platform terms, version metadata and contributor provenance. An initial licensing review is not permission to ingest or redistribute a collection.

## Existing systems deserve careful comparison

IkengaTTS is an important recent Igbo TTS reference. It demonstrates that meaningful Igbo synthesis development is already happening. We have not reproduced its reported results. Our proposed work investigates explicit tone and phoneme supervision, dialect control, native-speaker evaluation and permissive infrastructure through controlled comparisons.

Meta MMS provides multilingual speech research baselines. Its TTS licence includes non-commercial restrictions, and exact task and checkpoint coverage must be checked. It is therefore a possible reference baseline, rather than an assumed permanent foundation for a permissively released Igbo system.

NCAIR and Awarri publish Igbo ASR and multilingual language work, including N-ATLaS. These initiatives show a growing Nigerian-language AI ecosystem. Their release terms and underlying model conditions require individual review. Listing them here does not indicate a collaboration or independent endorsement of performance claims.

## Research in a wider community

Masakhane is an important African NLP community spanning translation, named entity recognition, classification, question answering and evaluation. Igbo AI intends to engage with this ecosystem respectfully. Collaboration should begin with listening, attribution and clearly agreed contributions. None of the external projects in this review are being announced as Igbo AI partners.

## The infrastructure gap

Our initial landscape review did not identify a single mature open project bringing pronunciation, tone, phonetics, dialects, verified speech, TTS, ASR, native-speaker evaluation, tooling and responsible provenance together. This is a bounded finding from an initial review, not an absolute claim that no such effort exists. We welcome corrections and additional references.

The proposed response is a connected foundation: IgboPronounce, IgboTone and IgboPhonemizer; a carefully verified IgboSpeech Gold collection; IgboSpeechBench; dialect-conditioned TTS and permissive ASR; and community recording and evaluation infrastructure. Later language intelligence can build on this work. These are planned outputs, not existing releases.

## The first research question

Can explicit tone, phoneme and dialect supervision make an Igbo speech system measurably more native-sounding than existing character-based Igbo TTS and general-purpose AI voices?

This remains a question. A useful study would hold data and evaluation conditions as consistent as possible, compare linguistic supervision choices, include names and code-switching, and combine automated metrics with blind native-speaker listening. We have not run that benchmark or demonstrated superiority.

## What happens next

The initial technology landscape, dataset/model inventory, licensing landscape and major-gap identification are complete. Phase 0 remains In Progress: potential collaborator mapping is underway, while a formal provenance audit, academic and community consultation and an initial benchmark specification remain planned.

The linked Landscape page is a living register maintained through the Research Desk. Each reference records its review date, access considerations and provisional role. Corrections, missing resources and research enquiries are welcome at support@igbo.ai. No external data or model weights have been incorporated into an Igbo AI release by publishing this review.','Igbo AI · Galaxyway AI','Published','2026-09-05T15:13:05.073Z','An initial review of Igbo speech data, NLP, TTS, ASR, licensing and the open linguistic infrastructure still needed.');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','igboapi');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','waxal');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','common-voice');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','fleurs');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','african-voices');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','ikengatts');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','mms');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','ncair-asr');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','natlas');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','igbobert');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','igboberta');
INSERT INTO research_update_resources(update_id,resource_id) VALUES('landscape-review-v01','masakhane');
INSERT INTO audit_log(id,actor,action,entity_type,entity_id,new_value) VALUES('phase2-roadmap','Phase 2 owner-approved migration','update','roadmap','phase-0','Initial review completed; phase remains In Progress');
INSERT INTO audit_log(id,actor,action,entity_type,entity_id,new_value) VALUES('phase2-publication','Phase 2 owner-approved migration','publish','updates','landscape-review-v01','Landscape Review v0.1 with reviewed references');
