-- September 2026 research review metadata. Existing records are retained.
ALTER TABLE resources ADD COLUMN resource_type TEXT NOT NULL DEFAULT 'Research resource';
ALTER TABLE resources ADD COLUMN provider TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN release_version TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN publisher_coverage TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN code_licence TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN model_licence TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN dataset_licence TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN training_permission TEXT NOT NULL DEFAULT 'Unknown — review required';
ALTER TABLE resources ADD COLUMN redistribution_status TEXT NOT NULL DEFAULT 'Unknown — review required';
ALTER TABLE resources ADD COLUMN commercial_use TEXT NOT NULL DEFAULT 'Unknown — review required';
ALTER TABLE resources ADD COLUMN contributor_consent TEXT NOT NULL DEFAULT 'Unknown — review required';
ALTER TABLE resources ADD COLUMN provenance_status TEXT NOT NULL DEFAULT 'Initial assessment';
ALTER TABLE resources ADD COLUMN evidence_status TEXT NOT NULL DEFAULT 'Documentation reviewed';
ALTER TABLE resources ADD COLUMN uncertainties TEXT NOT NULL DEFAULT '';
INSERT INTO site_settings(key,value) VALUES ('landscape_review_date','2026-09-19') ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP;
UPDATE resources SET resource_type='Dataset',provider='Google Research / Media Trust',publisher_coverage='Igbo TTS subset; aggregate WAXAL headline hours are not Igbo hours',dataset_licence='CC BY-SA 4.0 for the listed Igbo TTS subset',training_permission='Subject to release-specific audit',redistribution_status='Subject to share-alike and manifest review',commercial_use='Unknown — provider terms require review',contributor_consent='Not independently verified',provenance_status='Manifest-level audit pending',evidence_status='Documentation reviewed',uncertainties='Aggregate card totals are not a reliable Igbo quantity; verify the exact contribution and version.' WHERE id='waxal';
UPDATE resources SET publisher_coverage='Approximately 25,500 single-word recordings and 25,000 sentence recordings reported by the dataset card; not a count of distinct words',resource_type='Dataset / Pronunciation',provider='Nkọwa okwu',release_version='Current gated repository release',dataset_licence='CC BY 4.0 according to the dataset card',training_permission='Access agreement and contributor permissions require review',redistribution_status='Gated; no redistribution assumption',commercial_use='Unknown — review required',contributor_consent='Provenance and recording permissions require review',provenance_status='Version and speaker audit pending',evidence_status='Documentation reviewed',uncertainties='Exact version, access terms, speakers and conditions alongside CC BY 4.0 require inspection.' WHERE id='ibo-dict';
UPDATE resources SET publisher_coverage='Public overall totals are inconsistent across platform descriptions',dataset_licence='CC BY wording appears with additional platform conditions',training_permission='Permission and platform conditions require reconciliation',contributor_consent='Not independently verified',provenance_status='Dataset-specific audit pending',evidence_status='Documentation reviewed',uncertainties='Reconcile public totals, release metadata and platform terms before any ingestion.' WHERE id='african-voices';
UPDATE resources SET dataset_licence='CC0-1.0 for the reviewed release; platform conditions separate',release_version='Scripted Speech 26.0 (June 2026)',evidence_status='Documentation reviewed',uncertainties='Keep release metadata and no-identification/no-resharing platform restrictions visible.' WHERE id='common-voice';
UPDATE resources SET model_licence='CC BY-NC-SA 4.0 stated by the model card',code_licence='F5-TTS dependency terms require separate review',training_permission='Unknown — source and base-model terms require review',redistribution_status='Non-commercial/share-alike restrictions',commercial_use='Not assumed',evidence_status='Documentation reviewed',uncertainties='Do not generalise one model-card observation about tone input; test conditions directly.' WHERE id='ikengatts';
UPDATE resources SET code_licence='Apache 2.0 for the published code/model family',model_licence='Apache 2.0 family terms; exact checkpoint review required',publisher_coverage='Meta reports 729.6 training hours and 9.1 CER for the named original 7B evaluation',training_permission='Reference-only until release terms are checked',redistribution_status='Checkpoint-specific review required',commercial_use='Check exact checkpoint and dependencies',contributor_consent='Not applicable to published model card; source data audit remains separate',provenance_status='Publisher documentation reviewed',evidence_status='Documentation reviewed',uncertainties='729.6 hours and 9.1 CER are publisher-reported results for the named 7B evaluation, not Igbo AI reproduction or every checkpoint.' WHERE id='meta-omnilingual-asr';
UPDATE resources SET resource_type='Speech model / code',provider='k2-fsa',code_licence='Apache 2.0',model_licence='CC BY-NC for pretrained weights',training_permission='Unknown — source data review required',redistribution_status='Weights restricted by non-commercial terms',commercial_use='Not assumed',evidence_status='Documentation reviewed',uncertainties='Igbo coverage is a comparator signal, not proof of native-quality pronunciation.' WHERE id='omnivoice';
UPDATE resources SET resource_type='Dataset',provider='NaijaVoices',publisher_coverage='Approximately 600 hours each for Igbo, Hausa and Yoruba are publisher-reported; another batch description implies a different total',dataset_licence='CC BY-NC-SA 4.0 default; waiver route is conditional',training_permission='Conditional waiver or default terms require review',redistribution_status='Non-commercial/share-alike by default',commercial_use='Not permitted by default',contributor_consent='Review contributor and waiver terms',provenance_status='Public documentation reviewed; totals inconsistent',evidence_status='Documentation reviewed',uncertainties='Do not describe the waiver as unrestricted or permanent.' WHERE id='naijavoices';
UPDATE resources SET resource_type='Speech translation research',provider='NaijaS2ST authors',publisher_coverage='Approximately 50 hours per named Nigerian language according to the paper abstract',dataset_licence='File-level rights require review',training_permission='Unknown — review required',redistribution_status='Unknown — review required',commercial_use='Unknown — review required',contributor_consent='Unknown — review required',provenance_status='Paper reviewed; files pending',evidence_status='Documentation reviewed',uncertainties='April 2026 paper; verify available files, rights and overlap with other collections.' WHERE id='naijas2st';
UPDATE resources SET resource_type='Research paper',provider='Paper authors',publisher_coverage='Igbo diacritic restoration methods and corpus-based baselines',evidence_status='Documentation reviewed',uncertainties='The 2026 archive date does not mean every method was newly developed in 2026.' WHERE id='igbo-diacritic-restoration';
UPDATE resources SET resource_type='Dataset',provider='Mozilla Data Collective',dataset_licence='NOODL terms stated by the dataset page',training_permission='Excluded from planned generative TTS training pool unless express permission is obtained',redistribution_status='Restricted',commercial_use='Prohibited by the stated terms',contributor_consent='Terms require review',provenance_status='Documentation reviewed',evidence_status='Documentation reviewed',uncertainties='No generative AI, speaker imitation or commercial use without separate express permission.' WHERE id='igbo-tts-dataset';
UPDATE resources SET resource_type='Language model',provider='Qwen',release_version='Qwen3-8B',code_licence='Apache 2.0',model_licence='Apache 2.0',training_permission='Model terms require later review',redistribution_status='Checkpoint-specific review required',commercial_use='Check current model terms',evidence_status='Documentation reviewed',uncertainties='Optional later IgboLM baseline; refresh shortlist when Phase 6 begins.' WHERE id='qwen3-8b';
INSERT INTO resources(id,title,organisation,category,summary,url,licence,licence_url,access_status,potential_role,notes,last_reviewed_at,verified,status,resource_type,provider,release_version,publisher_coverage,code_licence,model_licence,dataset_licence,training_permission,redistribution_status,commercial_use,contributor_consent,provenance_status,evidence_status,uncertainties) VALUES
('meta-omnilingual-asr','Meta Omnilingual ASR','Meta AI','ASR','A multilingual speech recognition family and priority comparator for early Igbo baseline testing.','https://github.com/facebookresearch/omnilingual-asr','Apache 2.0 code/model family','https://github.com/facebookresearch/omnilingual-asr','Model/checkpoint review','Benchmark','Meta reports 729.6 training hours and 9.1 CER for a named original 7B evaluation; this is publisher-reported, not reproduced by Igbo AI.','2026-09-19',0,'Published','Speech model / code','Meta AI','Original 7B evaluation','Igbo row and named evaluation only; do not generalise to later checkpoints','Apache 2.0','Apache 2.0 family terms','Source data and checkpoint terms require review','Reference only until exact release is checked','Checkpoint-specific review','Check exact checkpoint','Source data provenance separate','Publisher documentation reviewed','Documentation reviewed','Result scope and later checkpoints require separate review.'),
('omnivoice','OmniVoice','k2-fsa','TTS','A multilingual speech model with Igbo coverage, useful as a research comparator.','https://huggingface.co/k2-fsa/OmniVoice','Apache 2.0 code; CC BY-NC weights','https://huggingface.co/k2-fsa/OmniVoice','Non-commercial weights','Benchmark','Separate code terms from pretrained-weight terms; coverage does not establish native-quality pronunciation.','2026-09-19',0,'Published','Speech model / code','k2-fsa','Current model card','Igbo listed among covered languages','Apache 2.0','CC BY-NC','Training data requires review','Weights restricted','Not assumed','Unknown — review required','Source data audit pending','Documentation reviewed','Documentation reviewed','Commercial/open-weight release route is not assumed.'),
('naijavoices','NaijaVoices','NaijaVoices','Dataset','Nigerian-language speech collection with publisher-reported Igbo, Hausa and Yoruba quantities and conditional licensing.','https://huggingface.co/datasets/naijavoices/naijavoices-dataset','CC BY-NC-SA 4.0 default; conditional waiver route','https://naijavoices.com/license-agreement','Conditional waiver / non-commercial default','Investigate','Public totals are inconsistent across descriptions; reconcile manifests, speaker permissions and waiver conditions.','2026-09-19',0,'Published','Dataset','NaijaVoices','Current dataset page','Approximately 600 hours per language claimed; another batch description differs','','','CC BY-NC-SA 4.0 default','Conditional; review waiver','Non-commercial/share-alike by default','Not permitted by default','Review required','Public documentation reviewed','Documentation reviewed','Totals and waiver conditions require re-review.'),
('naijas2st','NaijaS2ST','NaijaS2ST authors','Speech translation','April 2026 speech-translation research reporting approximately 50 hours per named Nigerian language in the abstract.','https://arxiv.org/abs/2604.16287','Paper and file terms require review','https://arxiv.org/abs/2604.16287','Files and rights require review','Investigate','Review file availability, source provenance and overlap with other speech collections before reuse.','2026-09-19',0,'Published','Speech translation research','NaijaS2ST authors','April 2026 paper','Approximately 50 hours per named language per abstract','','','File-level rights unknown','Unknown — review required','Unknown — review required','Unknown — review required','Unknown — review required','Paper reviewed; files pending','Documentation reviewed','File availability, rights and overlap are unresolved.'),
('igbo-diacritic-restoration','Corpus-Based Approaches to Igbo Diacritic Restoration','Research paper authors','NLP / Orthography','Background and baseline research for IgboTone and uncertainty-aware diacritic restoration.','https://arxiv.org/abs/2601.18380','Paper access does not establish data or code reuse rights','https://arxiv.org/abs/2601.18380','Paper review','Investigate','The 2026 archive date does not imply all methods are new in 2026.','2026-09-19',0,'Published','Research paper','Paper authors','2026 archive record','Igbo diacritic restoration methods and corpus-based baselines','','','','Unknown — review required','Unknown — review required','Unknown — review required','Unknown — review required','Paper reviewed','Documentation reviewed','Method provenance and artefact licences require review.'),
('igbo-tts-dataset','Igbo-TTS-Dataset (Mozilla Data Collective)','Mozilla Data Collective','Dataset','Restricted Igbo speech dataset excluded from the planned generative TTS training pool unless separate express permission is obtained.','https://mozilladatacollective.com/datasets/cmp0f5u2n02a8mp0771ryoly8','NOODL terms; generative AI, speaker imitation and commercial use restricted','https://mozilladatacollective.com/datasets/cmp0f5u2n02a8mp0771ryoly8','Restricted / express permission required','Exclude for intended use','Retain as a rights boundary record; do not ingest or train from it under the default terms.','2026-09-19',0,'Published','Dataset','Mozilla Data Collective','Current dataset page','Igbo TTS collection; exact quantity requires review','','','NOODL terms','Express permission required','Restricted','Prohibited by stated terms','Terms reviewed','Documentation reviewed','No generative AI, speaker imitation or commercial use without separate express permission.','Default terms do not permit intended generative use.'),
('qwen3-8b','Qwen3-8B','Qwen','Language Model','Optional later IgboLM baseline with Apache 2.0 terms; refresh the shortlist when Phase 6 begins.','https://huggingface.co/Qwen/Qwen3-8B','Apache 2.0','https://huggingface.co/Qwen/Qwen3-8B','Later-stage review','Benchmark','This is an optional baseline, not a claim that it is newest or best for Igbo.','2026-09-19',0,'Published','Language model','Qwen','Qwen3-8B','General model coverage; Igbo task performance not yet evaluated','Apache 2.0','Apache 2.0','Training data provenance separate','Checkpoint-specific review','Check current terms','Source data review separate','Documentation reviewed','Documentation reviewed','Refresh model shortlist before Phase 6.','Refresh shortlist at Phase 6.'),
('f5-tts','F5-TTS','SWivid','TTS / Code','Open speech synthesis code useful for a controlled permissive-code baseline after dependency and weight review.','https://github.com/SWivid/F5-TTS','Code licence and dependencies require review','https://github.com/SWivid/F5-TTS','Dependency review','Benchmark','Code terms do not override restrictions on data or pretrained weights.','2026-09-19',0,'Published','Speech synthesis code','SWivid','Current repository','General TTS framework; no Igbo result claimed','','','Code and dependency terms require review','Unknown — review required','Unknown — review required','Not applicable to code alone','Repository reviewed','Documentation reviewed','Use only after dependency, weight and data audit.','Dependency and weight audit pending.'),
('vits','VITS','jaywalnut310','TTS / Code','A controlled code baseline candidate for later speech experiments after dependency and weight review.','https://github.com/jaywalnut310/vits','MIT code; dependencies and weights require review','https://github.com/jaywalnut310/vits','Dependency review','Benchmark','A permissive code licence does not make source data or weights permissive.','2026-09-19',0,'Published','Speech synthesis code','jaywalnut310','Current repository','General TTS framework; no Igbo result claimed','MIT','','Source data and weights require review','Unknown — review required','Unknown — review required','Not applicable to code alone','Repository reviewed','Documentation reviewed','Review dependencies and checkpoint terms before use.','Dependency and checkpoint audit pending.');
INSERT INTO research_updates(id,slug,title,summary,content,author_organisation,status,published_at,seo_description)
VALUES('september-2026-review','igbo-ai-research-and-delivery-review-2026','Igbo AI Research and Delivery Review — September 2026','A desk review that sharpens the evidence gates from research readiness to a bounded first pronunciation or TTS proof.','## What we reviewed

We reviewed current Igbo speech, pronunciation, ASR, TTS, language-model and licensing resources, including the newer Meta Omnilingual ASR, OmniVoice, NaijaVoices, NaijaS2ST, diacritic-restoration research, a restricted Igbo TTS dataset and a later Qwen3-8B comparator. The living landscape records individual sources, access conditions, uncertainties and review dates.

## What remains unchanged

Igbo AI remains a speech-first, open and evidence-led programme operated and led by Galaxyway AI Ltd. No proprietary Igbo AI model, production TTS or ASR service, corpus, assistant or voice-collection study has been released through this programme.

## What changed in the delivery direction

We will test current systems before building at scale, treat rights and contributor permissions as architecture decisions, and establish an independent benchmark before expanding data or model scope. The first public technical objective is one bounded, rights-cleared Standard Igbo pronunciation or single-voice TTS proof evaluated against named baselines. Dialect and conversational claims will remain narrower until community review and evidence support them. Existing components may be adopted, adapted, integrated or contributed to when their evidence and terms fit the intended use.

## Phase 0 remains in progress

The initial and expanded desk reviews are complete. A formal provenance audit, sample inspection, community and academic consultation, contributor agreements, model reproduction and the first benchmark specification remain outstanding unless separately evidenced. Phase 0 must establish at least one plausible documented release path and named technical and linguistic leadership before later gates open.

## The six evidence-gated delivery phases

Phase 1 develops a bounded IgboPronounce, IgboTone and IgboPhonemizer foundation. Phase 2 defines IgboSpeechBench with held-out challenge material and blind native-speaker review. Phase 3 tests one authorised Standard Igbo voice with matched grapheme, reviewed-tone and phoneme-plus-tone conditions. Phase 4 considers two additional community-defined varieties with multiple principal speakers. Phase 5 evaluates current ASR before targeted adaptation. Phase 6 starts with one narrow adult-facing language task and compares retrieval, tools and small adaptations before any broad language-model programme.

## How to help

Igbo linguists and phonologists, native speakers and educators, speech researchers, data engineers, universities, resource maintainers and organisations with grants, sponsorship, computing, recording facilities or staff time can help. Scope, credit, payment where applicable, ownership and publication arrangements will be agreed before work starts. Use the collaboration form or contact the sponsorship team to discuss a defined role.

## Limits of this review

This is a desk review and delivery plan. It is not a completed provenance audit, model-training exercise, native-speaker study or performance result. Publisher-reported figures remain attributed to their sources, and legal review is still required before ingestion, redistribution, training or release. See the living landscape, roadmap and data-ethics pages for the working records.','Igbo AI · Galaxyway AI','Published','2026-09-19T12:00:00.000Z','Igbo AI research and delivery review for September 2026: evidence gates, rights, benchmarks and the bounded first speech proof.');
INSERT INTO research_update_resources(update_id,resource_id) SELECT 'september-2026-review',id FROM resources WHERE id IN ('meta-omnilingual-asr','omnivoice','naijavoices','naijas2st','igbo-diacritic-restoration','igbo-tts-dataset','qwen3-8b','ibo-dict');
INSERT INTO audit_log(id,actor,action,entity_type,entity_id,new_value) VALUES('september-2026-review','Owner-requested research review','publish','updates','september-2026-review','Desk review and delivery plan published; no model or dataset release implied');

